Repository fga-eps-mds/2020.1-VC_Usuario-FrontEnd, pull requests merged in 2020-10, with the labels that each got.

#11 US05 #126 Cadastro
  src/assets/visibilidade.png
  src/services/registros.js
  src/views/Cadastro.vue
Labels: enhancement, hacktoberfest-accepted

#13 US06 #130 fazer/desfazer login
  package-lock.json
  package.json
  src/components/Header.vue
  src/components/MenuBar.vue
  src/main.js
  src/router/index.js
  src/services/config.js
  src/services/postagens.js
  src/services/registros.js
  src/services/usuarios.js
  src/store/index.js
  src/views/Cadastro.vue
  src/views/Editar.vue
  src/views/Login.vue
  src/views/Perfil.vue
Labels: hacktoberfest-accepted

#14 Feature/us11 12 13 14 #144 tela de perfil de usuario
  src/assets/edit.png
  src/assets/trophy.png
  src/router/index.js
  src/views/Editar.vue
  src/views/Perfil.vue
Labels: development, enhancement, hacktoberfest-accepted

#16 148 importar stylesheets
  src/assets/stylesheets/font.scss
  src/assets/stylesheets/pallete.scss
  src/components/Header.vue
  src/components/MenuBar.vue
  src/components/PostagemComponent.vue
  src/views/Cadastro.vue
  src/views/CriarPostagem.vue
  src/views/Editar.vue
  src/views/Home.vue
  src/views/ListarUmaPostagem.vue
  src/views/Login.vue
Labels: development

#17 Atualização dos templates e README.
  .github/ISSUE_TEMPLATE/general-issue-template.md
  .github/pull_request_template.md
  README.md
Labels: documentation, enhancement

#15 US09 feed de noticias
  src/components/NoticiaComponent.vue
  src/router/index.js
  src/services/noticiaService.js
  src/views/FeedDeNoticias.vue
  src/views/VizualizarNoticia.vue
Labels: development, hacktoberfest-accepted

#18 #151 Resolvendo bug do botão voltar página não funcionar na header
  src/components/Header.vue
Labels: bug
