Repository fga-eps-mds/2020.1-VC_Usuario-FrontEnd, pull requests merged in 2020-12, with the labels that each got.

#35 197 arrumando bugs
  src/components/PostagemComponent.vue
  src/router/index.js
  src/services/postagensServices.js
  src/store/index.js
  src/views/CriarPostagem.vue
  src/views/EditarPostagem.vue
  src/views/Home.vue
  src/views/ListarUmaPostagem.vue
  src/views/Perfil.vue
Labels: development

#37 US20 #199 Denunciar Postagem
  src/components/PostagemComponent.vue
  src/services/postagensServices.js
  src/views/ListarUmaPostagem.vue
Labels: development

#38 Ajustes gerais
  .env
  src/components/ComentarioComponent.vue
  src/components/NoticiaComponent.vue
  src/components/PostagemComponent.vue
  src/store/index.js
  src/views/CriarPostagem.vue
  src/views/EditarPerfil.vue
  src/views/EditarPostagem.vue
  src/views/Home.vue
  src/views/ListarUmaPostagem.vue
  src/views/Perfil.vue
Labels: bug, development, enhancement

#39 #216 Ajustando mudança e estilo do status
  src/components/PostagemComponent.vue
  src/router/index.js
  src/views/ListarUmaPostagem.vue
Labels: enhancement
