Repository fga-eps-mds/2020.1-VC_Usuario-FrontEnd, pull requests merged in 2020-11, with the labels that each got.

#19 US07 #136 Postagem Logado
  src/services/usuarios.js
  src/views/CriarPostagem.vue
  src/views/Home.vue
  src/views/ListarUmaPostagem.vue
  src/views/Perfil.vue
Labels: development, hacktoberfest-accepted

#21 168 Implementar Testes
  __test__/auxTestes.vue.test.js
  jest.config.js
  package-lock.json
  package.json
Labels: development

#22 Bugfix/#153 dados perdidos com refresh da pagina
  src/components/PostagemComponent.vue
  src/router/index.js
  src/store/index.js
  src/views/Home.vue
  src/views/ListarUmaPostagem.vue
Labels: bug

#23 Feature/us13 us14 #154 excluir/#155 editar conta
  src/services/usuarios.js
  src/store/index.js
  src/views/Editar.vue
  src/views/Login.vue
Labels: development

#24 Feature/us15 #161 filtrar postagens
  src/services/postagens.js
  src/views/Home.vue
Labels: development

#25 US11 US12 #166 Excluir e Editar Postagem
  src/assets/delete.png
  src/components/PostagemApoiadaComponent.vue
  src/components/PostagemComponent.vue
  src/router/index.js
  src/services/postagens.js
  src/views/EditarPostagem.vue
  src/views/ListarUmaPostagem.vue
  src/views/Perfil.vue
Labels: development

#26 #184 Refatorar Botão Apoiar
  src/components/PostagemApoiadaComponent.vue
  src/components/PostagemComponent.vue
  src/views/Home.vue
Labels: bug, development, enhancement

#27 Feature/us10#179 pontuacao
  src/store/index.js
  src/views/Perfil.vue
Labels: development

#28 176 padroes pwa
  public/img/icons/maskable_icon.png
  public/img/icons/vamosCuidarIcon-128x128.png
  public/img/icons/vamosCuidarIcon-144x144.png
  public/img/icons/vamosCuidarIcon-152x152.png
  public/img/icons/vamosCuidarIcon-192x192.png
  public/img/icons/vamosCuidarIcon-384x384.png
  public/img/icons/vamosCuidarIcon-512x512.png
  public/img/icons/vamosCuidarIcon-72x72.png
  public/img/icons/vamosCuidarIcon-96x96.png
  public/index.html
  public/manifest.json
  public/sw.js
  src/main.js
  src/registerServiceWorker.js
Labels: development

#30 Feature/us09 #191 acessar noticias
  .env
  src/components/MenuBar.vue
  src/components/NoticiaComponent.vue
  src/router/index.js
  src/services/config.js
  src/services/configNews.js
  src/services/noticiaService.js
  src/views/FeedDeNoticias.vue
  src/views/VizualizarNoticia.vue
Labels: development

#31 US22 #192 Usuário comentar postagem
  src/services/postagens.js
  src/views/ListarUmaPostagem.vue
Labels: development

#32 #187 Estilizando o Projeto
  public/favicon.ico
  public/img/icons/favicon-16x16.png
  public/img/icons/favicon-32x32.png
  public/img/icons/maskable_icon.png
  public/index.html
  public/manifest.json
  src/assets/addIcon.png
  src/assets/addIcon2.png
  src/assets/homeIcon2.png
  src/assets/newsIcon2.png
  src/assets/sidebar.png
  src/assets/stylesheets/pallete.scss
  src/assets/userIcon2.png
  src/components/Header.vue
  src/components/HeaderComponent.vue
  src/components/MenuBar.vue
  src/components/MenuBarComponent.vue
  src/components/PostagemComponent.vue
  src/router/index.js
  src/services/configServices.js
  src/services/postagensServices.js
  src/services/usuariosServices.js
  src/store/index.js
  src/views/Cadastro.vue
  src/views/CriarPostagem.vue
  src/views/Editar.vue
  src/views/EditarPerfil.vue
  src/views/EditarPostagem.vue
  src/views/FeedDeNoticias.vue
  src/views/Home.vue
  src/views/ListarUmaPostagem.vue
  src/views/Login.vue
  src/views/Perfil.vue
  src/views/VisualizarNoticia.vue
Labels: enhancement

#33 #187 Estilizando o Projeto
  src/components/PostagemComponent.vue
  src/services/postagensServices.js
  src/views/Cadastro.vue
  src/views/CriarPostagem.vue
  src/views/Home.vue
  src/views/ListarUmaPostagem.vue
  src/views/Login.vue
Labels: enhancement
